# Generated by Django 3.2.12 on 2022-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='select',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Error in task', 'Error in task')], default='', max_length=20),
        ),
    ]
